services:
  fuse_ubuntu:
    image: fuse_ubuntu_image
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fuse_ubuntu
    volumes:
      - ./source:/source
      - ./original_dir:/original_dir
      - ./mounted_dir:/mounted_dir
    stdin_open: true
    tty: true
    privileged: true
