services:
  fuse_ubuntu:
    image: fuse_ubuntu_image
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fuse_ubuntu
    volumes:
      - ./source:/source
      - ./original_dir:/original_dir
      - ./mounted_dir:/mounted_dir
    # command: "pip3 install -r /source/requirements.txt --break-system-packages"

    stdin_open: true
    tty: true
    privileged: true
